# Generated by Django 3.0.3 on 2020-05-10 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0004_auto_20200216_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='entry_category',
            field=models.ForeignKey(blank=True, default='Random', null=True, on_delete=django.db.models.deletion.CASCADE, to='entries.Category'),
        ),
    ]
